name: CI

env:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v1
      with:
        path: .m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set tag or branch
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: Check RELEASE_VERSION
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      run: |
        echo $RELEASE_VERSION

    - name: maven test
      run: mvn $MAVEN_CLI_OPTS test

    - name: maven build
      run: mvn $MAVEN_CLI_OPTS package

    - name: upload jar file
      if: contains(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v2-preview
      with:
        path: target/*.jar
        name: jar

    - name: Docker login
      if: contains(github.ref, 'refs/tags/')
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: build image
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      if: contains(github.ref, 'refs/tags/')
      run: docker build -t sadomasupilami/ba-api-github:$RELEASE_VERSION .

    - name: push image
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      if: contains(github.ref, 'refs/tags/')
      run: docker push ${{ secrets.DOCKER_USERNAME }}/ba-api-github:$RELEASE_VERSION
